// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCmcUwQ0Lw8yJJJP4TdlbdA3sc_iudIs',
    appId: '1:865856877296:web:e74c0b3c679a21eb570835',
    messagingSenderId: '865856877296',
    projectId: 'prueba-jp-d952c',
    authDomain: 'prueba-jp-d952c.firebaseapp.com',
    databaseURL: 'https://prueba-jp-d952c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-jp-d952c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjeAJkLcIgzhQhOhznjoIwqh9RRhchRlI',
    appId: '1:865856877296:android:0cee2b9241062a19570835',
    messagingSenderId: '865856877296',
    projectId: 'prueba-jp-d952c',
    databaseURL: 'https://prueba-jp-d952c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-jp-d952c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnPlSRt4lr1EJ7cBXTewHOY88mZSpEfTQ',
    appId: '1:865856877296:ios:c090e9f8121b431d570835',
    messagingSenderId: '865856877296',
    projectId: 'prueba-jp-d952c',
    databaseURL: 'https://prueba-jp-d952c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-jp-d952c.appspot.com',
    iosBundleId: 'com.example.appAa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnPlSRt4lr1EJ7cBXTewHOY88mZSpEfTQ',
    appId: '1:865856877296:ios:c090e9f8121b431d570835',
    messagingSenderId: '865856877296',
    projectId: 'prueba-jp-d952c',
    databaseURL: 'https://prueba-jp-d952c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-jp-d952c.appspot.com',
    iosBundleId: 'com.example.appAa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwCmcUwQ0Lw8yJJJP4TdlbdA3sc_iudIs',
    appId: '1:865856877296:web:ae01b6e57400b5e5570835',
    messagingSenderId: '865856877296',
    projectId: 'prueba-jp-d952c',
    authDomain: 'prueba-jp-d952c.firebaseapp.com',
    databaseURL: 'https://prueba-jp-d952c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-jp-d952c.appspot.com',
  );
}
